# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contingent', '0002_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_monitor',
            field=models.BooleanField(default=False, verbose_name='\u0421\u0442\u0430\u0440\u043e\u0441\u0442\u0430'),
        ),
    ]
