# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contingent', '0004_remove_student_is_monitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsgroup',
            name='monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor_group', to='contingent.Student', verbose_name='\u0421\u0442\u0430\u0440\u043e\u0441\u0442\u0430'),
        ),
    ]
