# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contingent', '0005_studentsgroup_monitor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['user__surname']},
        ),
    ]
