# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-17 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contingent', '0009_position'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Position',
            new_name='PositionType',
        ),
    ]
