# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-17 10:46
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contingent', '0011_employmenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='\u0410\u043a\u0442\u0438\u0432\u043d\u044b\u0439')),
                ('date_from', models.DateTimeField(verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0442')),
                ('date_to', models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0434\u043e')),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, verbose_name='\u0421\u0442\u0430\u0432\u043a\u0430')),
                ('employment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contingent.EmploymentType', verbose_name='\u0412\u0438\u0434 \u0437\u0430\u043d\u044f\u0442\u043e\u0441\u0442\u0438')),
                ('position_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contingent.PositionType', verbose_name='\u0414\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u044c')),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='contingent.Subdivision', verbose_name='\u041f\u043e\u0434\u0440\u0430\u0437\u0434\u0435\u043b\u0435\u043d\u0438\u0435')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to=settings.AUTH_USER_MODEL, verbose_name='\u0421\u043e\u0442\u0440\u0443\u0434\u043d\u0438\u043a')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
