# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-17 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contingent', '0012_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdivision',
            name='chief',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chief_subdivisions', to='contingent.Position', verbose_name='\u0417\u0430\u0432\u0435\u0434\u0443\u044e\u0449\u0438\u0439'),
        ),
    ]
