# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-12 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contingent', '0013_subdivision_chief'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScientificManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisers', to='contingent.Student', verbose_name='\u0421\u0442\u0443\u0434\u0435\u043d\u0442')),
                ('superviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scientific_students', to='contingent.Teacher', verbose_name='\u041d\u0430\u0443\u0447\u043d\u044b\u0439 \u0440\u0443\u043a\u043e\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u044c')),
            ],
        ),
    ]
