# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-13 07:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contingent', '0015_auto_20160412_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientificmanagement',
            name='active_flag',
            field=models.BooleanField(default=False, verbose_name='\u0410\u043a\u0442\u0438\u0432\u043d\u0430\u044f'),
        ),
        migrations.AddField(
            model_name='scientificmanagement',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 13, 7, 8, 22, 731146, tzinfo=utc), verbose_name='\u0412\u0440\u0435\u043c\u044f \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scientificmanagement',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 4, 13, 7, 8, 28, 451006, tzinfo=utc), verbose_name='\u0412\u0440\u0435\u043c\u044f \u043c\u043e\u0434\u0438\u0444\u0438\u043a\u0430\u0446\u0438\u0438'),
            preserve_default=False,
        ),
    ]
