# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 11:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(verbose_name='\u0422\u0435\u043c\u0430')),
                ('message', models.TextField(verbose_name='\u0421\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0435')),
                ('to', models.ManyToManyField(related_name='mailings', to=settings.AUTH_USER_MODEL, verbose_name='\u041a\u043e\u043c\u0443')),
            ],
        ),
    ]
