# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_mailing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteuser',
            options={'ordering': ['surname']},
        ),
        migrations.AddField(
            model_name='mailing',
            name='is_delivered',
            field=models.BooleanField(default=False, verbose_name='\u0414\u043e\u0441\u0442\u0430\u0432\u043b\u0435\u043d\u043e'),
        ),
    ]
