# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20160215_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='date_delivery',
            field=models.DateTimeField(default=None, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0442\u043f\u0440\u0430\u0432\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='is_delivered',
            field=models.BooleanField(default=False, verbose_name='\u041e\u0442\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u043e'),
        ),
    ]
