# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_auto_20160215_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='date_delivery',
            field=models.DateTimeField(default=None, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0442\u043f\u0440\u0430\u0432\u043a\u0438'),
        ),
    ]
