# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 10:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_auto_20160216_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingstatus',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing_statuses', to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u0443\u0447\u0430\u0442\u0435\u043b\u044c'),
        ),
    ]
