# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_mailingstatus_redirect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingstatus',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u043c\u043e\u0434\u0438\u0444\u0438\u043a\u0430\u0446\u0438\u0438'),
        ),
    ]
