# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-10 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_mailingstatus_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='message_txt',
            field=models.TextField(blank=True, null=True, verbose_name='\u0421\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0435 txt'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='message',
            field=models.TextField(verbose_name='\u0421\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0435 html'),
        ),
    ]
