# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-07 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_auto_20160310_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='test_email',
            field=models.CharField(blank=True, max_length=2014, null=True, verbose_name='\u0442\u0435\u0441\u043c\u0442\u043e\u0432\u044b\u0439 e-mail'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='test_flag',
            field=models.BooleanField(default=False, verbose_name='\u0422\u0435\u0441\u0442\u043e\u0432\u0430\u044f \u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0430'),
        ),
    ]
