# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-24 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gendoc', '0002_generateddocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedDocumentProcessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('clazz', models.CharField(max_length=1024, verbose_name='\u041a\u043b\u0430\u0441\u0441')),
            ],
        ),
        migrations.AddField(
            model_name='generateddocumenttemplate',
            name='processor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gendoc.GeneratedDocumentProcessor', verbose_name='\u0413\u0435\u043d\u0435\u0440\u0430\u0442\u043e\u0440 \u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u0430'),
        ),
    ]
