# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-24 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gendoc', '0003_auto_20160324_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddocumenttemplate',
            name='template_info',
            field=models.TextField(blank=True, null=True, verbose_name='\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f \u043e \u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u0435'),
        ),
    ]
