# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(related_name='courses_teacher', to='contingent.Teacher', verbose_name='\u0423\u0447\u0438\u0442\u0435\u043b\u044f'),
        ),
    ]
