# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contingent', '0007_teacher'),
        ('training', '0002_auto_20160229_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogramm',
            name='creatos',
            field=models.ManyToManyField(blank=True, related_name='course_programms', to='contingent.Teacher', verbose_name='\u0421\u043e\u0441\u0442\u0430\u0432\u0438\u0442\u0435\u043b\u0438'),
        ),
    ]
