# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_coursetask_coursetasksolution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursetask',
            options={'ordering': ['deadline_start']},
        ),
        migrations.AddField(
            model_name='coursetask',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='training.Course', verbose_name='\u041a\u0443\u0440\u0441'),
        ),
    ]
