# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_auto_20160301_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetasksolution',
            name='solutions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.BaseSolution', verbose_name='\u0420\u0435\u0448\u0435\u043d\u0438\u0435'),
        ),
    ]
