# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_auto_20160301_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetask',
            name='short_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='\u041a\u043e\u0440\u043e\u0442\u043a\u043e\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
    ]
