# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_auto_20160301_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='auto_check_code',
            field=models.TextField(blank=True, null=True, verbose_name='\u041a\u043e\u0434 \u0434\u043b\u044f \u0430\u0432\u0442\u043e\u043c\u0430\u0442\u0438\u0447\u0435\u0441\u043a\u043e\u0439 \u043f\u0440\u043e\u0432\u0435\u0440\u043a\u0438'),
        ),
    ]
