# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-10 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0013_auto_20160301_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursetasksolution',
            options={'ordering': ['task__num']},
        ),
    ]
