# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-14 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import training.models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0014_auto_20160310_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTaskSolutionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('attachment_file', models.FileField(upload_to=training.models.cts_upload, verbose_name='\u0424\u0430\u0439\u043b')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u043c\u043e\u0434\u0438\u0444\u0438\u043a\u0430\u0446\u0438\u0438')),
                ('cts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.CourseTaskSolution', verbose_name='\u0420\u0435\u0448\u0435\u043d\u0438\u0435 \u0437\u0430\u0434\u0430\u0447\u0438')),
            ],
        ),
    ]
