# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-17 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0015_coursetasksolutionfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursetasksolutionfile',
            options={'ordering': ['-created']},
        ),
    ]
